name: marktag
description: Flutter SDK for Marktag
version: 2.0.2
homepage: https://markopolo-inc.github.io/marktag-docs/
repository: https://github.com/markopolo-inc/marktag-sdk-flutter
issue_tracker: https://github.com/markopolo-inc/marktag-sdk-flutter/issues
topics:
  - marktag
  - analytics
  - flutter
  - dart

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  device_info_plus: ^13.1.0
  firebase_core: ">=2.24.0"
  firebase_messaging: ">=14.7.0"
  flutter:
    sdk: flutter
  http: ^1.4.0
  meta: ^1.17.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test_coverage_badge: ^0.3.2
  very_good_analysis: ^10.2.0
